[variables]
NIXPACKS_METADATA = "mini-trello-web"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @mini-trello/web build"]

[start]
cmd = "pnpm preview"