[build]
builder = "NIXPACKS"
buildCommand = "corepack enable && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile && pnpm build"
rootDirectory = "."
watchIgnorePaths = ["apps/api/**"]

[deploy]
startCommand = "corepack enable && corepack prepare pnpm@latest --activate && pnpm preview"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
httpPath = "/"
initialDelaySeconds = 10
periodSeconds = 30
timeoutSeconds = 10
successThreshold = 1
failureThreshold = 3