[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
httpPath = "/"
initialDelaySeconds = 10
periodSeconds = 30
timeoutSeconds = 10
successThreshold = 1
failureThreshold = 3