[variables]
NIXPACKS_METADATA = "mini-trello-monorepo"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

# Cette configuration sera overridée par les services individuels
[start]
cmd = "echo 'Use service-specific start commands'"