packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma

noHoist:
  - '@prisma/client'
  - '@prisma/engines'
