services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_trello
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    env_file:
      - ../.env.example
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    env_file:
      - ../.env.example
    ports:
      - "5173:80"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
