services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_trello
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: api
    env_file:
      - ../.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: web
    env_file:
      - ../.env
    ports:
      - "5173:80"

volumes:
  pgdata:
