[variables]
NIXPACKS_METADATA = "mini-trello-api"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter api build"]

[start]
cmd = "npx prisma migrate deploy && pnpm start"
