[variables]
NIXPACKS_METADATA = "mini-trello-api"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = [
  "cd ../..",
  "pnpm install --frozen-lockfile --prefer-offline"
]

[phases.build]
cmds = [
  "cd ../..",
  "pnpm --filter api build",
  "cd apps/api",
  "pnpm prisma generate"
]

[start]
cmd = "./start.sh"
