[variables]
NIXPACKS_METADATA = "mini-trello-api"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.build]
cmds = ["./railway-build.sh"]

[start]
cmd = "cd apps/api && npx prisma migrate deploy && node dist/index.js"
