[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "corepack"]

[phases.install] 
cmds = [
  "./setup-pnpm.sh",
  "cd ../..",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../..",
  "pnpm --filter api build"
]

[start]
cmd = "./start.sh"