[build]
builder = "NIXPACKS"
buildCommand = "./setup-pnpm.sh"
rootDirectory = "."
watchIgnorePaths = ["apps/web/**"]

[deploy]
startCommand = "npm install -g pnpm@latest && pnpm db migrate deploy && node dist/index.js"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
httpPath = "/health"
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
successThreshold = 1
failureThreshold = 3